### ISSUE TITLE
Render map for Tab 1

### ISSUE THREAD

**Issue by caraconnachan** [Improvement-Service/pop_projections_shiny_tool#13]
- Renderleaflet using merged data and shape file

- Map zoomed into selected council

- Require input from council selection (means this map will only show once council is selected)

- Use stored colour values as fill

- Add legend - Smallest population to largest population

- Add labels - Selected area name, year, ages, gender, total population value

**Comment by caraconnachan** [comment]
Need to add this output to the Ui - Add 2nd conditionalPanel, if council input is not blank show council map - outputID = la_map_tab_1
Add a blank absolute panel

**Comment by NMCassidy** [comment]
Hi - in my issue I have to create the colour palette that goes into this map. Would it be possible to change it slightly so that the colour palette is generated within this reactive function i.e. using _colorBin(map_colours, DATASET)_. I think this would be tidier, as the input will be from a reactive function (I think).

**Comment by caraconnachan** [comment]
I've now submitted a pull request for the code and I've create the colour palette within this. I don't think there is any reactive input to this but I think you're right that it probably makes sense to do it within this, I think for the other map the colours may need to be set manually so I think I had got confused. I'm not sure if I've actually done it right but we can see when we test it. 
Also I realised I had created a separate issue for the Ui part so I haven't done that under this issue.
